"""Init DB

Revision ID: 13d26c470ee5
Revises: 
Create Date: 2020-06-20 18:31:47.605831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f76448bb6de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('mail', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=True)
    op.create_table('domain_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_template_name'), 'domain_template', ['name'], unique=True)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=256), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('master', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('serial', sa.BigInteger(), nullable=True),
    sa.Column('notified_serial', sa.BigInteger(), nullable=True),
    sa.Column('last_check', sa.Integer(), nullable=True),
    sa.Column('dnssec', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_name'), 'domain', ['name'], unique=True)
    op.create_table('domain_template_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['domain_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('otp_secret', sa.String(length=16), nullable=True),
    sa.Column('confirmed', sa.SmallInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('account_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_apikey',
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('apikey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikey.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], )
    )
    op.create_table('domain_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('setting', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('comments_name_type_idx', table_name='comments')
    op.drop_index('comments_order_idx', table_name='comments')
    op.drop_table('comments')
    op.drop_index('domainidindex', table_name='cryptokeys')
    op.drop_table('cryptokeys')
    op.drop_index('domainmetadata_idx', table_name='domainmetadata')
    op.drop_table('domainmetadata')
    op.drop_index('nametype_index', table_name='records')
    op.drop_table('records')
    op.drop_table('supermasters')
    op.drop_index('name_index', table_name='domains')
    op.drop_table('domains')
    op.drop_index('namealgoindex', table_name='tsigkeys')
    op.drop_table('tsigkeys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tsigkeys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('algorithm', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('secret', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('namealgoindex', 'tsigkeys', ['name', 'algorithm'], unique=True)
    op.create_table('domains',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('master', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last_check', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('notified_serial', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account', mysql.VARCHAR(charset='utf8', length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name_index', 'domains', ['name'], unique=True)
    op.create_table('supermasters',
    sa.Column('ip', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('nameserver', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('account', mysql.VARCHAR(charset='utf8', length=40), nullable=False),
    sa.PrimaryKeyConstraint('ip', 'nameserver'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('records',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=64000), nullable=True),
    sa.Column('ttl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('prio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('disabled', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ordername', mysql.VARCHAR(charset='latin1', collation='latin1_bin', length=255), nullable=True),
    sa.Column('auth', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('nametype_index', 'records', ['name', 'type'], unique=False)
    op.create_table('domainmetadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kind', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('domainmetadata_idx', 'domainmetadata', ['domain_id', 'kind'], unique=False)
    op.create_table('cryptokeys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('flags', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('domainidindex', 'cryptokeys', ['domain_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('domain_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('modified_at', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('account', mysql.VARCHAR(charset='utf8', length=40), nullable=True),
    sa.Column('comment', mysql.TEXT(charset='utf8'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('comments_order_idx', 'comments', ['domain_id', 'modified_at'], unique=False)
    op.create_index('comments_name_type_idx', 'comments', ['name', 'type'], unique=False)
    op.drop_table('domain_user')
    op.drop_table('domain_setting')
    op.drop_table('domain_apikey')
    op.drop_table('account_user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('domain_template_record')
    op.drop_index(op.f('ix_domain_name'), table_name='domain')
    op.drop_table('domain')
    op.drop_table('apikey')
    op.drop_table('setting')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_table('history')
    op.drop_index(op.f('ix_domain_template_name'), table_name='domain_template')
    op.drop_table('domain_template')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
